### ISSUE TITLE
Error a la hora de instalar desde el repositorio de Foundry VTT

### ISSUE THREAD

**Issue by Damaskian** [Dentatum/degenesis-foundryvtt-compendium-esp#1]
¡Buenas! He intentado instalar el módulo pero me sale un error. 

La única forma que he podido hacerlo es bajándome el zip del repositorio github y cambiando el **id** del **module.json** de _'degenesis-esp'_ a _'degenesis-foundryvtt-compendium-esp'_

Aquí una captura del error en Foundry.

![image](https://github.com/Dentatum/degenesis-foundryvtt-compendium-esp/assets/70920540/c7e014bf-70d3-4b23-9ff6-8c190c54eb38)

**Comment by Dentatum** [comment]
Buenas, gracias por avisar y disculpa!
Actualizo el manifiesto, creo que ya debería funcionar

**Comment by Damaskian** [comment]
Mmm sigue dando problemas. No se si es porque tiene el _/blob/_ en la url del manifest o por que falta la línea de _'download'_.

O puede ser que github tarda en actualizar el repositorio así que será cuestión de esperar un rato.

**Comment by Dentatum** [comment]
Vale, instalación limpia y ahora sí me ha dejado...
Perdóname, es la primera vez que me estoy peleando con esto, te agradezco mucho la ayuda
